# -*- coding: utf-8 -*-
"""NBC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cltOGuJidB7Cr0HGvDmQCSBBFzPq8JEr
"""

! git clone https://github.com/SuhaasNachannagari/ToxicGamingProject-CS49000

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/ToxicGamingProject-CS49000/
!git pull

import pandas as pd
from sklearn.model_selection import train_test_split

merge = pd.read_csv("/content/ToxicGamingProject-CS49000/Database/merged_output.csv")
train_val, test = train_test_split(merge, test_size=245, random_state=42)
train, val = train_test_split(train_val, train_size=1962, random_state=42)

train.to_csv('/content/ToxicGamingProject-CS49000/Database/train.csv', index=False)
val.to_csv('/content/ToxicGamingProject-CS49000/Database/val.csv', index=False)
test.to_csv('/content/ToxicGamingProject-CS49000/Database/test.csv', index=False)

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

train = pd.read_csv("/content/ToxicGamingProject-CS49000/Database/train.csv")
val = pd.read_csv("/content/ToxicGamingProject-CS49000/Database/val.csv")
test = pd.read_csv("/content/ToxicGamingProject-CS49000/Database/test.csv")

tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
#scores the BoW

X_train = tfidf.fit_transform(train['message'])
X_val = tfidf.transform(val['message'])
X_test = tfidf.transform(test['message'])

#targets
y_train = train['new_label']
y_val = val['new_label']
y_test = test['new_label']

#start training
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)
print("Model training complete")

#run validation set
val_preds = nb_model.predict(X_val)

#post-valid outputs
report_dict = classification_report(y_val, val_preds, output_dict=True)
report_df = pd.DataFrame(report_dict).transpose()
print("Validation Performance Table")
display(report_df)

cm = confusion_matrix(y_val, val_preds, labels=nb_model.classes_)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=nb_model.classes_,
            yticklabels=nb_model.classes_)
plt.title('DOTA 2 Classification: Actual vs. Predicted')
plt.xlabel('Predicted Label')
plt.ylabel('Actual Label')
plt.show()

# !!!!!!!!!!!!!!!!
# FINAL TEST SET EVALUATION (DO NOT RUN UNTIL FINAL MODEL EVAL)
# !!!!!!!!!!!!!!!

test_preds = nb_model.predict(X_test)

test_report_dict = classification_report(y_test, test_preds, output_dict=True)
test_report_df = pd.DataFrame(test_report_dict).transpose()

print("Final Test Set Results")
display(test_report_df)
cm_test = confusion_matrix(y_test, test_preds, labels=nb_model.classes_)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_test, annot=True, fmt='d', cmap='Greens',
            xticklabels=nb_model.classes_,
            yticklabels=nb_model.classes_)
plt.title('NBC Final Performance: Test Set')
plt.xlabel('Predicted Label')
plt.ylabel('Actual Label')
plt.show()